export 'package:popular_movies/core/widgets/animations/animated_entry_widget.dart';
export 'package:popular_movies/core/widgets/animations/animated_loading_bar.dart';
export 'package:popular_movies/core/widgets/custom_appbar.dart';
export 'package:popular_movies/core/widgets/w_profile_buttom.dart';
export 'package:popular_movies/core/widgets/custom_bottom_navigation_bar.dart';
export 'package:popular_movies/core/widgets/custom_button.dart';
export 'package:popular_movies/core/widgets/custom_divider.dart';
export 'package:popular_movies/core/widgets/custom_snackbar.dart';
export 'package:popular_movies/core/widgets/custom_text.dart';
